[general]
import = [
    "~/.config/alacritty/themes/nord.toml"
]

[window]
padding.y = 5
padding.x = 3
# padding.y = 20
# padding.x = 20
# opacity = 0.7

[font]
size = 7.4
# size = 8

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NL"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NL"
style = "Italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Bold"
