# [general]
# import = [
    # "~/.config/alacritty/themes/nord.toml"
# ]

[window]
padding.y = 4
padding.x = 4
opacity = 0.9

[font]
# size = 10.6
size = 12

[font.normal]
family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.bold]
family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.italic]
family = "Mx437 IBM VGA 8x16"
style = "Italic"

[font.bold_italic]
family = "Mx437 IBM VGA 8x16"
style = "Bold Italic"
