[general]
import = [
    "~/.config/alacritty/themes/one_dark.toml"
]

[font]
size = 7.4

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NL"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NL"
style = "Italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Bold"
