[general]
import = [
    "~/.config/alacritty/themes/nord.toml"
]

[window]
padding.y = 5
padding.x = 3
# padding.y = 20
# padding.x = 20
opacity = 0.7

[font]
# size = 7.4
size = 9.7

[font.normal]
# family = "JetBrains Mono NL"
family = "Mx437 IBM VGA 8x16"

[font.bold]
# family = "JetBrains Mono NL"
family = "Mx437 IBM VGA 8x16"
style = "Bold"

[font.italic]
# family = "JetBrains Mono NL"
family = "Mx437 IBM VGA 8x16"
style = "Italic"

[font.bold_italic]
# family = "JetBrains Mono NL"
family = "Mx437 IBM VGA 8x16"
style = "Bold Italic"
